### ISSUE TITLE
add code generation targets for mocks

### ISSUE THREAD

**Issue by aucampia** [coopnorge/go-datadog-lib#24]
It would be nice if there was a target for generatin mocks with go-mock. It could be incorporated it with the use of [devtools-golang](https://github.com/coopnorge/go-datadog-lib/issues/17)

**Comment by aucampia** [comment]
For previous discussion:

- https://github.com/coopnorge/go-datadog-lib/issues/17

**Comment by aucampia** [comment]
> @aucampia That request is not a responsibility of this repository scope. If you still like it move it where that belongs to.

While you are not using devtools-golang this is in the scope of this repo.

**Comment by nhhagen** [comment]
I have to agree with @aucampia here. It is the responsibility of the repository to make it easy for new engineers to contribute. Our dev tools-golang facilitates this.

My recommendation is to use devtool-golang that way the repository does not have to re-implement existing code.

**Comment by LinMAD** [comment]
Not convinced, this datadog repository, and if it required any changes outside this scope that belongs somewhere else if you are willing to add the same way of working with mocks to your devtools then add it there as a new feature.

**Comment by JustAdam** [comment]
Not sure why this issue keeps getting closed, when it is not being addressed.

Solutions have been pointed on resolving this, let's instead close this issue when it is resolved.

**Comment by LinMAD** [comment]
Because it's not related. Mock can be generated via go mocks, or via an aggregator, it's the developer's responsibility which way to use it.

One more time, if a question related to the integration of mock aggregation to common image "devtools" then that must be done outside this repository. If there are suggestions then open PR with changes, more than that it was discussed already I don't see the point to spend here more time.

**Comment by nhhagen** [comment]
Mock generation is now included in golang-devtools and the relevant documentation here is updated.
